
Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:14:23 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:14:23 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:16:10 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:16:10 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:17:28 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:17:28 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

com.microsoft.sqlserver.jdbc.SQLServerException: Syntaxe incorrecte vers 'asDECLARE'.
  -> ERROR 01/03/20 15:17:30 - com.avista.vues.FSaveMAJ.executeProcedureSave(FSaveMAJ.java:160)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:19:32 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:19:32 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:21:45 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:21:46 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

com.microsoft.sqlserver.jdbc.SQLServerException: Il existe déjà un objet nommé 'sauvegardeExfiles' dans la base de données.
  -> ERROR 01/03/20 15:21:48 - com.avista.vues.FSaveMAJ.executeProcedureSave(FSaveMAJ.java:160)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:31:05 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:31:05 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

com.microsoft.sqlserver.jdbc.SQLServerException: Il existe déjà un objet nommé 'sauvegardeExfiles' dans la base de données.
  -> ERROR 01/03/20 15:31:07 - com.avista.vues.FSaveMAJ.executeProcedureSave(FSaveMAJ.java:160)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:34:15 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:34:15 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

com.microsoft.sqlserver.jdbc.SQLServerException: Il existe déjà un objet nommé 'sauvegardeExfiles' dans la base de données.
  -> ERROR 01/03/20 15:34:17 - com.avista.vues.FSaveMAJ.executeProcedureSave(FSaveMAJ.java:161)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:37:31 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:37:31 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

com.microsoft.sqlserver.jdbc.SQLServerException: Syntaxe incorrecte vers 'REPLACE'.
  -> ERROR 01/03/20 15:37:33 - com.avista.vues.FSaveMAJ.executeProcedureSave(FSaveMAJ.java:161)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:38:33 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:38:33 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:39:22 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:39:22 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)

Réussite de la connexion de l'utilisateur
  -> DEBUG 01/03/20 15:44:20 - com.avista.dao.UtilisateurDAO.authentifierUtilisateur(UtilisateurDAO.java:44)

Réussite de l'exécution des requêtes
  -> DEBUG 01/03/20 15:44:20 - com.avista.dao.PiniDAO.VersionActuelle(PiniDAO.java:40)
